name = "my-app"
compatibility_date = "2024-10-25"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "my-app-dev"
database_id = "ae57ca8d-eb72-459f-b93f-36545e2b35f1"
migrations_dir = "drizzle"

# [ai]
# binding = "AI"